AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  VpcCidrRange:
    Type: String
    Description: CIDR range for the VPC
    Default: 10.0.0.0/16

  Subnet1CidrRange:
    Type: String
    Description: CIDR range for Subnet 1
    Default: 10.0.1.0/24

  Subnet2CidrRange:
    Type: String
    Description: CIDR range for Subnet 2
    Default: 10.0.2.0/24

  Subnet3CidrRange:
    Type: String
    Description: CIDR range for Subnet 3
    Default: 10.0.3.0/24

  VpcName:
    Type: String
    Description: Name of the VPC

Resources:
  BaseVPCStack:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc-base.yaml
      Parameters:
        VpcCidrRange: !Ref VpcCidrRange
        Subnet1CidrRange: !Ref Subnet1CidrRange
        Subnet2CidrRange: !Ref Subnet2CidrRange
        Subnet3CidrRange: !Ref Subnet3CidrRange
        VpcName: !Ref VpcName

  EndpointsStack:
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./endpoints.yaml
      Parameters:
        VpcId: !GetAtt BaseVPCStack.Outputs.VpcId
        SubnetIds: !GetAtt BaseVPCStack.Outputs.SubnetIds